import { useState } from "react";
import { BookOpen, RotateCcw } from "lucide-react";
import ReadingExam, { type ReadingAttemptAnswer } from "@/components/ReadingExam";
import readingExamData from "@/data/readingExamData.json";

const STORAGE_KEY = "siele-leitura-editor-v2";

export default function Home() {
  const [started, setStarted] = useState(false);
  const [startMode, setStartMode] = useState<"edit" | "take">("edit");
  const [saved, setSaved] = useState<ReadingAttemptAnswer[] | null>(null);
  const reset = () => { localStorage.removeItem(STORAGE_KEY); setSaved(null); setStarted(false); setStartMode("edit"); };
  const complete = (answers: ReadingAttemptAnswer[]) => { setSaved(answers); localStorage.setItem(STORAGE_KEY, JSON.stringify({ answers, finishedAt: new Date().toISOString() })); };
  if (started) return <ReadingExam initialQuestions={readingExamData as ReadingAttemptAnswer[]} initialMode={startMode} onComplete={complete} />;
  return <div className="min-h-screen bg-[#f1f1f1] text-[#333]" style={{ fontFamily: "Lato, Arial, sans-serif" }}><header className="border-b border-[#263746] bg-[#34404d]"><div className="mx-auto flex min-h-[74px] max-w-[1100px] items-center justify-between px-5"><div className="flex items-center gap-3"><img src="/praticasieleespanhol/img/header.png" className="h-12 w-auto max-w-[310px] object-contain object-left" alt="SIELE" /><span className="hidden text-xs font-bold text-white/80 sm:block">Prática de compreensão de leitura</span></div><span className="text-xs font-bold text-white">ES | PT | EN</span></div></header><main className="mx-auto max-w-[820px] px-5 py-14"><section className="border border-[#c9c9c9] bg-white p-7 shadow-sm sm:p-10"><div className="mb-6 flex h-12 w-12 items-center justify-center rounded-full bg-[#b08b2c] text-white"><BookOpen /></div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#9a781f]">Prática SIELE · Leitura</p><h1 className="mt-2 text-3xl font-bold text-[#34404d]">Escolha como começar</h1><p className="mt-3 max-w-[650px] text-sm leading-6 text-[#555]">Prepare o conteúdo da Prova 1 no modo de edição ou entre diretamente no modo de execução para responder ao exame.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><button onClick={() => { setStartMode("edit"); setStarted(true); }} className="rounded bg-[#34404d] px-5 py-5 text-left text-white"><strong className="block text-base">Editar a prova</strong><span className="mt-2 block text-xs leading-5 text-white/75">Alterar textos, enunciados e opções nos locais correspondentes antes de iniciar.</span></button><button onClick={() => { setStartMode("take"); setStarted(true); }} className="rounded border-2 border-[#b08b2c] bg-[#fffaf0] px-5 py-5 text-left text-[#5b4815]"><strong className="block text-base">Fazer o exame</strong><span className="mt-2 block text-xs leading-5 text-[#6d6040]">Abrir diretamente a prova para escolher alternativas e usar os menus dentro do texto.</span></button></div>{saved && <div className="mt-6 flex items-center justify-between border border-[#a8c9bd] bg-[#e8f3ee] p-4 text-xs"><span>Última tentativa salva: {saved.length} registros.</span><button onClick={reset} className="inline-flex items-center gap-1 font-bold text-[#28755e]"><RotateCcw size={13} /> Limpar</button></div>}</section></main><footer className="mt-10 bg-[#34404d] px-5 py-5 text-center text-xs text-white/80">Ferramenta de prática · não é um produto oficial SIELE</footer></div>;
}
